# Generated by Django 2.1.2 on 2020-07-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='費用'),
        ),
        migrations.AddField(
            model_name='process',
            name='necessary_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='所要時間'),
        ),
    ]
